In [1]:
# Python import
import os
import copy
import random
import collections
import itertools
import numpy as np
import pandas as pd
import lightgbm as lgb
from sklearn import svm
import warnings
import joblib
from sklearn.model_selection import train_test_split,RandomizedSearchCV
import sklearn.metrics as metrics
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score, roc_auc_score, f1_score, average_precision_score
import csv

In [2]:
def LR_kftest(X_train, y_train, X_test, y_test, SEED):    
    # Logistic Regression params
    lr_param_dict = {
        "penalty": ["l2"],
        "C": [1e-3, 5e-3, 1e-2, 0.05, 0.1, 0.5, 1, 5, 10, 50, 100, 500, 1000],
        "solver": ["liblinear"],
        "random_state": [SEED]
    }

    # Initiate Logistic Regression model
    lr_model = LogisticRegression()

    # Adjust hyper-parameters with randomized search
    lr_rscv = RandomizedSearchCV(lr_model, lr_param_dict, n_iter=100, cv=5, verbose=0,
                                 scoring="roc_auc", random_state=SEED, n_jobs=-1)
    lr_rscv.fit(X_train, y_train)

    # Predict on the test set
    y_pred = lr_rscv.best_estimator_.predict(X_test)
    y_pred_proba = lr_rscv.best_estimator_.predict_proba(X_test)[:, 1]

    # Calculate metrics
    acc = accuracy_score(y_test, y_pred)
    auroc = roc_auc_score(y_test, y_pred_proba)
    f1 = f1_score(y_test, y_pred)
    aurp = average_precision_score(y_test, y_pred_proba)

    return acc, auroc, f1, aurp

In [3]:
# Output result of evaluation
def eval_output(model_perf,path):
    with open(os.path.join(path,"Evaluate_Result_TestSet.txt"),'w') as f:
        f.write("AUROC=%s\tAUPRC=%s\tAccuracy=%s\tMCC=%s\tRecall=%s\tPrecision=%s\tf1_score=%s\n" %
               (model_perf["auroc"],model_perf["auprc"],model_perf["accuracy"],model_perf["mcc"],model_perf["recall"],model_perf["precision"],model_perf["f1"]))
        f.write("\n######NOTE#######\n")
        f.write("#According to help_documentation of sklearn.metrics.classification_report:in binary classification, recall of the positive class is also known as sensitivity; recall of the negative class is specificity#\n\n")
        f.write(model_perf["class_report"])

In [ ]:
def equal_kind(data_df):
    df_y0 = data_df[data_df['label'] == 0]
    df_y1 = data_df[data_df['label'] == 1]

    # Determine the smaller count between the two subsets
    min_count = min(len(df_y0), len(df_y1))

    # Randomly sample equally from both subsets
    df_y0_balanced = df_y0.sample(n=min_count, random_state=42) if len(df_y0) > min_count else df_y0
    df_y1_balanced = df_y1.sample(n=min_count, random_state=42) if len(df_y1) > min_count else df_y1

    # Combine and shuffle the balanced subsets
    balanced_df = pd.concat([df_y0_balanced, df_y1_balanced])
    balanced_df = balanced_df.sample(frac=1, random_state=42).reset_index(drop=True)
    return balanced_df

In [ ]:
def prepare_full_dataset(label_folder_path, sample_folder_path, features_num):
    """
    Merge all samples and labels into a single dataset.
    
    :param label_folder_path: Path to label folder
    :param sample_folder_path: Path to sample folder
    :param features_num: Number of features for training
    :return: Numpy arrays of features and labels
    """
    label_csv_files = sorted([f for f in os.listdir(label_folder_path) if f.endswith('.csv')])
    sample_csv_files = sorted([f for f in os.listdir(sample_folder_path) if f.endswith('.csv')])

    all_labels, all_samples = [], []

    for label_file, sample_file in zip(label_csv_files, sample_csv_files):
        all_labels.append(pd.read_csv(os.path.join(label_folder_path, label_file)))
        all_samples.append(pd.read_csv(os.path.join(sample_folder_path, sample_file)))

    all_labels_df = pd.concat(all_labels, axis=0)
    all_samples_df = pd.concat(all_samples, axis=0)
    merged_df = pd.merge(all_samples_df, all_labels_df, on='sample', how='left')
    merged_df = equal_kind(merged_df)

    features = merged_df.iloc[:, 1:features_num + 1].values  # Extract feature columns
    labels = merged_df.iloc[:, -1].values  # Extract label columns

    return features, labels

In [6]:
# Plot AUROC of model
def plot_AUROC(model_perf,path):
    #get AUROC,FPR,TPR and threshold
    roc_auc = model_perf["auroc"]
    fpr,tpr,threshold = model_perf["auroc_curve"]
    #return AUROC info
    temp_df = pd.DataFrame({"FPR":fpr,"TPR":tpr})
    temp_df.to_csv(os.path.join(path,"AUROC_info.txt"),header = True,index = False, sep = '\t')
    #plot
    plt.figure()
    lw = 2
    plt.figure(figsize=(10,10))
    plt.plot(fpr, tpr, color='darkorange',
             lw=lw, label='AUROC (area = %0.2f)' % roc_auc) 
    plt.plot([0, 1], [0, 1], color='navy', lw=lw, linestyle='--')
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.0])
    plt.xlabel("False Positive Rate")
    plt.ylabel("True Positive Rate")
    plt.title("AUROC of Models")
    plt.legend(loc="lower right")
    plt.savefig(os.path.join(path,"AUROC_TestSet.pdf"),format = "pdf")

In [7]:
# Random seed
SEED = 100
random.seed(SEED)
np.random.seed(SEED)

warnings.filterwarnings(action='ignore')

In [ ]:
label_folder_path = './resources/NomalSamples/labels/'
sample_folder_path = './resources/NomalSamples/samples/'
features_nums = [640, 600, 560, 520, 480, 440, 400, 360, 320, 280, 240, 200, 160, 120, 80, 40]
all_results = []

for features_num in features_nums:
    print(f"Running with features_num = {features_num}")
    X, y = prepare_full_dataset(label_folder_path, sample_folder_path, features_num=features_num)
    kf = KFold(n_splits=5, shuffle=True, random_state=SEED)

    fold_accuracies, fold_auroc, fold_F1, fold_aurp = [], [], [], []

    for fold, (train_index, val_index) in enumerate(kf.split(X)):
        print(f"Training fold {fold + 1}")
        X_train, X_val = X[train_index], X[val_index]
        y_train, y_val = y[train_index], y[val_index]

        acc, auroc, F1, aurp = LR_kftest(X_train, y_train, X_val, y_val, SEED)
        
        fold_accuracies.append(acc)
        fold_auroc.append(auroc)
        fold_F1.append(F1)
        fold_aurp.append(aurp)

    results = {
        "features_num": features_num,
        "mean_accuracy": np.mean(fold_accuracies),
        "accuracy_variance": np.var(fold_accuracies),
        "mean_auroc": np.mean(fold_auroc),
        "auroc_variance": np.var(fold_auroc),
        "mean_F1": np.mean(fold_F1),
        "F1_variance": np.var(fold_F1),
        "mean_aurp": np.mean(fold_aurp),
        "aurp_variance": np.var(fold_aurp)
    }
    all_results.append(results)

csv_file = './ML_models/eight_sample_11features_test/5fold_features_ablation/LR_ablation_results.csv'
file_exists = os.path.isfile(csv_file)

with open(csv_file, mode='a', newline='') as file:
    writer = csv.DictWriter(file, fieldnames=results.keys())
    if not file_exists:
        writer.writeheader()
    for result in all_results:
        writer.writerow(result)

print("Experiment completed and results saved.")

Running with features_num = 640
Training fold 1
Training fold 2
Training fold 3
Training fold 4
Training fold 5
Running with features_num = 600
Training fold 1
Training fold 2
Training fold 3
Training fold 4
Training fold 5
Running with features_num = 560
Training fold 1
Training fold 2
Training fold 3
Training fold 4
Training fold 5
Running with features_num = 520
Training fold 1
Training fold 2
Training fold 3
Training fold 4
Training fold 5
Running with features_num = 480
Training fold 1
Training fold 2
Training fold 3
Training fold 4
Training fold 5
Running with features_num = 440
Training fold 1
Training fold 2
Training fold 3
Training fold 4
Training fold 5
Running with features_num = 400
Training fold 1
Training fold 2
Training fold 3
Training fold 4
Training fold 5
Running with features_num = 360
Training fold 1
Training fold 2
Training fold 3
Training fold 4
Training fold 5
Running with features_num = 320
Training fold 1
Training fold 2
Training fold 3
Training fold 4
Training fold 5
Running with features_num = 280
Training fold 1
Training fold 2
Training fold 3
Training fold 4
Training fold 5
Running with features_num = 240
Training fold 1
Training fold 2
Training fold 3
Training fold 4
Training fold 5
Running with features_num = 200
Training fold 1
Training fold 2
Training fold 3
Training fold 4
Training fold 5
Running with features_num = 160
Training fold 1
Training fold 2
Training fold 3
Training fold 4
Training fold 5
Running with features_num = 120
Training fold 1
Training fold 2
Training fold 3
Training fold 4
Training fold 5
Running with features_num = 80
Training fold 1
Training fold 2
Training fold 3
Training fold 4
Training fold 5
Running with features_num = 40
Training fold 1
Training fold 2
Training fold 3
Training fold 4
Training fold 5
Experiment completed and results saved.

In [ ]:
# Feature ablation in reverse order, starting with coverage
label_folder_path = './resources/NomalSamples/labels/'
sample_folder_path = './resources/NomalSamples/samples/'
features_nums = [640, 600, 560, 520, 480, 440, 400, 360, 320, 280, 240, 200, 160, 120, 80, 40]
all_results = []

label_csv_files = sorted([f for f in os.listdir(label_folder_path) if f.endswith('.csv')])
sample_csv_files = sorted([f for f in os.listdir(sample_folder_path) if f.endswith('.csv')])

all_labels, all_samples = [], []
for label_file, sample_file in zip(label_csv_files, sample_csv_files):
    all_labels.append(pd.read_csv(os.path.join(label_folder_path, label_file)))
    all_samples.append(pd.read_csv(os.path.join(sample_folder_path, sample_file)))

all_labels_df = pd.concat(all_labels, axis=0)
all_samples_df = pd.concat(all_samples, axis=0)
merged_df = pd.merge(all_samples_df, all_labels_df, on='sample', how='left')
merged_df = equal_kind(merged_df)

first_col = merged_df.iloc[:, 0]
last_col = merged_df.iloc[:, -1]
middle_cols_reversed = merged_df.iloc[:, 1:-1].iloc[:, ::-1]
merged_df_reordered = pd.concat([first_col, middle_cols_reversed, last_col], axis=1)

for features_num in features_nums:
    print(f"Running with features_num = {features_num}")
    X = merged_df_reordered.iloc[:, 1:features_num + 1].values
    y = merged_df_reordered.iloc[:, -1].values
    kf = KFold(n_splits=5, shuffle=True, random_state=SEED)

    fold_accuracies, fold_auroc, fold_F1, fold_aurp = [], [], [], []

    for fold, (train_index, val_index) in enumerate(kf.split(X)):
        print(f"Training fold {fold + 1}")
        X_train, X_val = X[train_index], X[val_index]
        y_train, y_val = y[train_index], y[val_index]

        acc, auroc, F1, aurp = LR_kftest(X_train, y_train, X_val, y_val, SEED)
        
        fold_accuracies.append(acc)
        fold_auroc.append(auroc)
        fold_F1.append(F1)
        fold_aurp.append(fold_aurp)

    results = {
        "features_num": features_num,
        "mean_accuracy": np.mean(fold_accuracies),
        "accuracy_variance": np.var(fold_accuracies),
        "mean_auroc": np.mean(fold_auroc),
        "auroc_variance": np.var(fold_auroc),
        "mean_F1": np.mean(fold_F1),
        "F1_variance": np.var(fold_F1),
        "mean_aurp": np.mean(fold_aurp),
        "aurp_variance": np.var(fold_aurp)
    }
    all_results.append(results)

csv_file = './ML_models/eight_sample_11features_test/5fold_features_ablation/LR_ablation_reveresd_results.csv'
file_exists = os.path.isfile(csv_file)

with open(csv_file, mode='a', newline='') as file:
    writer = csv.DictWriter(file, fieldnames=results.keys())
    if not file_exists: writer.writeheader()
    for result in all_results:
        writer.writerow(result)

print("Experiment completed and results saved.")

Running with features_num = 640
Training fold 1
Training fold 2
Training fold 3
Training fold 4
Training fold 5
Running with features_num = 600
Training fold 1
Training fold 2
Training fold 3
Training fold 4
Training fold 5
Running with features_num = 560
Training fold 1
Training fold 2
Training fold 3
Training fold 4
Training fold 5
Running with features_num = 520
Training fold 1
Training fold 2
Training fold 3
Training fold 4
Training fold 5
Running with features_num = 480
Training fold 1
Training fold 2
Training fold 3
Training fold 4
Training fold 5
Running with features_num = 440
Training fold 1
Training fold 2
Training fold 3
Training fold 4
Training fold 5
Running with features_num = 400
Training fold 1
Training fold 2
Training fold 3
Training fold 4
Training fold 5
Running with features_num = 360
Training fold 1
Training fold 2
Training fold 3
Training fold 4
Training fold 5
Running with features_num = 320
Training fold 1
Training fold 2
Training fold 3
Training fold 4
Training fold 5
Running with features_num = 280
Training fold 1
Training fold 2
Training fold 3
Training fold 4
Training fold 5
Running with features_num = 240
Training fold 1
Training fold 2
Training fold 3
Training fold 4
Training fold 5
Running with features_num = 200
Training fold 1
Training fold 2
Training fold 3
Training fold 4
Training fold 5
Running with features_num = 160
Training fold 1
Training fold 2
Training fold 3
Training fold 4
Training fold 5
Running with features_num = 120
Training fold 1
Training fold 2
Training fold 3
Training fold 4
Training fold 5
Running with features_num = 80
Training fold 1
Training fold 2
Training fold 3
Training fold 4
Training fold 5
Running with features_num = 40
Training fold 1
Training fold 2
Training fold 3
Training fold 4
Training fold 5
Experiment completed and results saved.

In [ ]:
label_folder_path = './resources/NomalSamples/labels/'
sample_folder_path = './resources/NomalSamples/samples/'
label_csv_files = sorted([f for f in os.listdir(label_folder_path) if f.endswith('.csv')])
sample_csv_files = sorted([f for f in os.listdir(sample_folder_path) if f.endswith('.csv')])

all_labels, all_samples = [], []
for label_file, sample_file in zip(label_csv_files, sample_csv_files):
    all_labels.append(pd.read_csv(os.path.join(label_folder_path, label_file)))
    all_samples.append(pd.read_csv(os.path.join(sample_folder_path, sample_file)))

all_labels_df = pd.concat(all_labels, axis=0)
all_samples_df = pd.concat(all_samples, axis=0)
merged_df = pd.merge(all_samples_df, all_labels_df, on='sample', how='left')
merged_df = equal_kind(merged_df)
merged_df

,sample,cov_1,cov_2,cov_3,cov_4,cov_5,cov_6,cov_7,cov_8,cov_9,...,struc112,struc113,struc114,struc115,struc116,struc117,struc118,struc119,struc120,label
0,promoter__chr17___16439436____16443036_pos|598...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1,0,0,1,0,0,1,0,0,0
1,promoter__chr6___26312414____26314414_neg|1800...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1,0,0,1,0,0,1,0,0,1
2,enhancer__chr9___35657203____35663203_neg|5183...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0,0,1,1,0,0,1,0,0,0
3,NR_145822_____1|4185|diff,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1,0,0,1,0,0,1,0,0,1
4,enhancer__chr6___27662663____27671263_neg|678|...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1,0,0,1,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2671,L1MEd__chr6___157012070____157012304_pos|136|diff,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1,0,0,1,0,0,1,0,0,1
2672,ENST00000385230_____1|21|same,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1,0,0,1,0,0,1,0,0,0
2673,ENST00000408479_____1|71|same,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1,0,0,1,0,0,1,0,0,0
2674,NR_146117_____1|11610|same,0.365759,0.346304,0.175097,0.089494,0.085603,0.046693,0.046693,0.046693,0.046693,...,0,0,1,1,0,0,1,0,0,0
2675,ENST00000385011_____1|26|same,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1,0,0,1,0,0,1,0,0,0

In [ ]:


merged_df_reordered

,sample,struc120,struc119,struc118,struc117,struc116,struc115,struc114,struc113,struc112,...,cov_9,cov_8,cov_7,cov_6,cov_5,cov_4,cov_3,cov_2,cov_1,label
0,promoter__chr17___16439436____16443036_pos|598...,0,0,1,0,0,1,0,0,1,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
1,promoter__chr6___26312414____26314414_neg|1800...,0,0,1,0,0,1,0,0,1,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1
2,enhancer__chr9___35657203____35663203_neg|5183...,0,0,1,0,0,1,1,0,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
3,NR_145822_____1|4185|diff,0,0,1,0,0,1,0,0,1,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1
4,enhancer__chr6___27662663____27671263_neg|678|...,0,0,1,0,0,1,0,0,1,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2671,L1MEd__chr6___157012070____157012304_pos|136|diff,0,0,1,0,0,1,0,0,1,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1
2672,ENST00000385230_____1|21|same,0,0,1,0,0,1,0,0,1,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
2673,ENST00000408479_____1|71|same,0,0,1,0,0,1,0,0,1,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
2674,NR_146117_____1|11610|same,0,0,1,0,0,1,1,0,0,...,0.046693,0.046693,0.046693,0.046693,0.085603,0.089494,0.175097,0.346304,0.365759,0
2675,ENST00000385011_____1|26|same,0,0,1,0,0,1,0,0,1,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0